### ISSUE TITLE
Unresolved Dependency

### ISSUE THREAD

**Issue by eluchsinger** [olaq/sbt-sonar-scanner-plugin#9]
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.olaq#sbt-sonar-scanner-plugin;1.1.0: not found

**Comment by olaq** [comment]
Are you using sbt 1.x?

**Comment by olaq** [comment]
Anyway, for sbt 1.x please use new version of plugin (1.3.0).

`addSbtPlugin("com.olaq" % "sbt-sonar-scanner-plugin" % "1.3.0")`
